group = osg.Group()
visitor = osg.ComputeBoundsVisitor()
print("About to send the visitor in.")
group:accept(visitor)
print("OK, sent the visitor in!")

print("About to grab the bbox")
bbox = visitor:getBoundingBox()
minX = bbox:minX()
print("OK, grabbed the bbox")
