assert(#(osg.Vec3Array().Item) == 0)
a = osg.Vec3Array()
a.Item:insert(osg.Vec3(0,0,0))
print(#(a.Item))
assert(#(a.Item) == 1)
print(a.Item[1])
assert(a.Item[1] == osg.Vec3(0,0,0))
a.Item[1] = osg.Vec3(1,1,1)
print(#(a.Item))
assert(#(a.Item) == 1)
assert(a.Item[1] == osg.Vec3(1,1,1))
